### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by CristianCantoro** [zehpunktbarron/iOSMAnalyzer#2]
I am sorry, but I can not understand the meaning of "Add the lines added in the attached files "handler.hpp" and "00-before.sql" to your version. ", to which attachments are you referring to?

Thanks.

Cristian

**Comment by zehpunktbarron** [comment]
Both files are added. Depending on the version of the osm-history-renderer you'll have to modify both files. Lines marked with "aaaaaaaaaaaaa" have to be added to ensure that user names and user ids are importet.
