### ISSUE TITLE
ERROR!c2_junctions.py

### ISSUE THREAD

**Issue by AbdulsalamAmin** [zehpunktbarron/iOSMAnalyzer#4]
hi
im run tool but error in c2_junctions.py script 
how to fix?
thanks

**Comment by afitas** [comment]
hi dear AbdulsalamAmin @AbdulsalamAmin
how did you install mapnik2 on your python envirenement please ?

**Comment by AbdulsalamAmin** [comment]
> hi dear AbdulsalamAmin @AbdulsalamAmin
> how did you install mapnik2 on your python envirenement please ?

hi dear afitas 
You need to install Ubuntu 12 or 14

**Comment by afitas** [comment]
thanks for your help

**Comment by AbdulsalamAmin** [comment]
> thanks for your help

thanks
